import { Geist, Geist_Mono,Inter } from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils"
import { ModeToggle } from "@/components/darkMode";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Inter({subsets: ['latin'], variable: "--font-poppins"});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(`${geistSans.variable} ${geistMono.variable} antialiased, poppins.className`)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            <ModeToggle/>
            {children}
            <Toaster richColors position="bottom-right" />
        </ThemeProvider>


        
      </body>
    </html>
  );
}
